# [[project]]
# name = ""
# desc = ""
# tags = ["", ""]
# links = [
#   { name = "", url = "" },
#   { name = "", url = "" },
# ]

[[project]]
name = "⚙ Dotfiles"
desc = "Opinionated compilation of configuration files and other related items. "
tags = ["neovim", "alacritty", "opinionated"]
links = [
  { name = "github", url = "https://github.com/semanticdata/dotfiles" },
  # { name = "", url = "" },
]

[[project]]
name = "🦊 Firefox Extensions"
desc = "Small group of utilitarian Firefox extensions I've put together mostly for personal use."
tags = ["firefox"]
links = [
  { name = "martketplace", url = "https://addons.mozilla.org/en-US/firefox/user/17772574/" },
  { name = "github", url = "https://github.com/semanticdata?tab=repositories&q=firefox&type=&language=&sort=" },
]

[[project]]
name = "🌱 Forgetful Notes"
desc = "My digital garden of knowledge. It serves as a platform for my learning and creative endeavours. A space for thinking through, building upon, and coming back to."
tags = ["digital-garden", "quartz", "quartz-website"]
links = [
  { name = "website", url = "https://forgetfulnotes.com/" },
  { name = "github", url = "https://github.com/semanticdata/forgetful-notes/" },
]

[[project]]
name = "🦎 Mabuya"
desc = "Minimal Zola theme focused on helping you build an elegant, fast, lightweight, and SEO-ready blog. Based on the Zola theme Tale."
tags = ["zola", "zola-theme"]
links = [
  { name = "demo", url = "https://miguelpimentel.do/mabuya/" },
  { name = "github", url = "https://github.com/semanticdata/mabuya/" },
]

[[project]]
name = "🔮 Obsidian Starter Vault"
desc = "Opinionated compilation of extensions and settings to help you learn and start exploring Obsidian."
tags = ["obsidian", "opinionated"]
links = [
  { name = "github", url = "https://github.com/semanticdata/obsidian-starter-vault/" },
  # { name = "", url = "" },
]

[[project]]
name = "📚 Zola Minimal"
desc = "Minimal—a Zola port of the Jekyll theme with the same name."
tags = ["zola", "zola-theme"]
links = [
  { name = "demo", url = " miguelpimentel.do/zola-minimal/" },
  { name = "github", url = "https://github.com/semanticdata/zola-minimal" },
]
